"""SGO v1.2.1 — Production Cutting Plan Excel Export.

Generates a multi-sheet XLSX from existing session-state results.
No recalculation — consumes packing_report, recovery_summary, and summary.
"""

import io
from datetime import datetime

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

SGO_VERSION = "v1.2.1"

_HEADER_FONT = Font(bold=True, color="FFFFFF", size=10)
_HEADER_FILL = PatternFill(start_color="1A1A2E", end_color="1A1A2E", fill_type="solid")
_THIN_BORDER = Border(
    left=Side(style="thin", color="CCCCCC"),
    right=Side(style="thin", color="CCCCCC"),
    top=Side(style="thin", color="CCCCCC"),
    bottom=Side(style="thin", color="CCCCCC"),
)
_PASS_FILL = PatternFill(start_color="E8F5E9", end_color="E8F5E9", fill_type="solid")
_FAIL_FILL = PatternFill(start_color="FFEBEE", end_color="FFEBEE", fill_type="solid")


def _style_header(ws, row, col_count):
    for col in range(1, col_count + 1):
        cell = ws.cell(row=row, column=col)
        cell.font = _HEADER_FONT
        cell.fill = _HEADER_FILL
        cell.alignment = Alignment(horizontal="center")
        cell.border = _THIN_BORDER


def _style_data(ws, start_row, end_row, col_count):
    for row in range(start_row, end_row + 1):
        for col in range(1, col_count + 1):
            cell = ws.cell(row=row, column=col)
            cell.border = _THIN_BORDER
            cell.alignment = Alignment(horizontal="left")


def _auto_width(ws, col_count, max_width=50):
    for col in range(1, col_count + 1):
        letter = get_column_letter(col)
        max_len = 0
        for row in ws.iter_rows(min_col=col, max_col=col, values_only=False):
            for cell in row:
                if cell.value:
                    max_len = max(max_len, len(str(cell.value)))
        ws.column_dimensions[letter].width = min(max_len + 4, max_width)


def _write_kpi_table(ws, title, rows, start_row=1):
    ws.cell(row=start_row, column=1, value=title).font = Font(bold=True, size=12)
    start_row += 1
    ws.cell(row=start_row, column=1, value="Metric")
    ws.cell(row=start_row, column=2, value="Value")
    _style_header(ws, start_row, 2)
    for i, (metric, value) in enumerate(rows, start=start_row + 1):
        ws.cell(row=i, column=1, value=metric)
        ws.cell(row=i, column=2, value=value)
    end_row = start_row + len(rows)
    _style_data(ws, start_row + 1, end_row, 2)
    return end_row + 2


def generate_excel(summary, packing_report, packing_summary,
                   recovery_summary=None, project_name="SGO Project") -> bytes:
    wb = Workbook()
    pk = packing_report["summary"]
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    # === Sheet 1: Executive Summary ===
    ws1 = wb.active
    ws1.title = "Executive Summary"

    row = _write_kpi_table(ws1, "Document Information", [
        ("Project Name", project_name),
        ("Generated Date", now),
        ("Generated By", "Steel Grating Optimizer"),
        ("SGO Version", SGO_VERSION),
        ("Algorithm", pk["algorithm"]),
    ])

    row = _write_kpi_table(ws1, "Project KPI", [
        ("Sold Area (m²)", f"{summary.total_sold_area:.4f}"),
        ("Production Area (m²)", f"{summary.total_production_area:.4f}"),
        ("Raw Material Area (m²)", f"{summary.total_raw_material_area:.4f}"),
        ("Yield (%)", f"{summary.yield_percent:.2f}"),
        ("Scrap (%)", f"{summary.scrap_percent:.2f}"),
    ], start_row=row)

    row = _write_kpi_table(ws1, "Packing KPI", [
        ("Stock Bars Required", pk["stock_lengths_after"]),
        ("Stock Bars Saved", f"{pk['stock_savings']} ({pk['stock_savings_percent']:.2f}%)"),
        ("Utilization (%)", f"{pk['stock_utilization_rate']:.2f}"),
        ("Items Packed", pk["total_items_packed"]),
        ("Marks Packed", pk["total_marks_packed"]),
    ], start_row=row)

    if recovery_summary is not None:
        row = _write_kpi_table(ws1, "Recovery KPI", [
            ("Recovery Rate (%)", f"{recovery_summary.recovery_rate:.2f}"),
            ("Recovered Area (m²)", f"{recovery_summary.recovered_area_m2:.4f}"),
            ("Dead Scrap Area (m²)", f"{recovery_summary.dead_scrap_area_m2:.4f}"),
            ("Remaining Stock Area (m²)", f"{recovery_summary.remaining_stock_area_m2:.4f}"),
        ], start_row=row)

    _auto_width(ws1, 2)

    # === Sheet 2: Production Cutting Plan ===
    ws2 = wb.create_sheet("Cutting Plan")
    headers = ["Bar", "Width (mm)", "Marks", "Panels", "Used (mm)", "Remnant (mm)", "Classification"]
    for col, h in enumerate(headers, 1):
        ws2.cell(row=1, column=col, value=h)
    _style_header(ws2, 1, len(headers))

    cutting_plan = packing_report["cutting_plan"]
    for i, cp in enumerate(cutting_plan, start=2):
        marks_text = ", ".join(f"{e['mark']} x {e['qty']}" for e in cp["entries"])
        ws2.cell(row=i, column=1, value=cp["bin_id"])
        ws2.cell(row=i, column=2, value=cp["stock_width"])
        ws2.cell(row=i, column=3, value=marks_text)
        ws2.cell(row=i, column=4, value=cp["total_panels"])
        ws2.cell(row=i, column=5, value=cp["total_used"])
        ws2.cell(row=i, column=6, value=cp["remnant_length"])
        ws2.cell(row=i, column=7, value=cp["remnant_classification"])

    _style_data(ws2, 2, len(cutting_plan) + 1, len(headers))
    _auto_width(ws2, len(headers))

    # === Sheet 3: Material Summary ===
    ws3 = wb.create_sheet("Material Summary")
    _write_kpi_table(ws3, "Material Summary", [
        ("Raw Material Area (m²)", f"{pk['total_raw_material_area_m2']:.4f}"),
        ("Product Area (m²)", f"{pk['total_product_area_m2']:.4f}"),
        ("Yield (%)", f"{summary.yield_percent:.2f}"),
        ("Reusable Remnant Area (m²)", f"{pk['total_reusable_remnant_area_m2']:.4f}"),
        ("Length Waste Area (m²)", f"{pk['total_length_waste_m2']:.4f}"),
        ("Kerf Loss Area (m²)", f"{pk['total_kerf_loss_m2']:.4f}"),
        ("Total Waste Area (m²)", f"{pk['total_waste_area_m2']:.4f}"),
    ])

    if recovery_summary is not None:
        _write_kpi_table(ws3, "Recovery Summary", [
            ("Recovered Area (m²)", f"{recovery_summary.recovered_area_m2:.4f}"),
            ("Recovery Rate (%)", f"{recovery_summary.recovery_rate:.2f}"),
            ("Dead Scrap Area (m²)", f"{recovery_summary.dead_scrap_area_m2:.4f}"),
            ("Remaining Stock Area (m²)", f"{recovery_summary.remaining_stock_area_m2:.4f}"),
        ], start_row=11)

    _auto_width(ws3, 2)

    # === Sheet 4: Validation ===
    ws4 = wb.create_sheet("Validation")
    val = packing_report["validation"]

    ws4.cell(row=1, column=1, value="Packing Validation (R22-R29)").font = Font(bold=True, size=12)
    status_text = f"{val['passed']} / {val['total']} {'ALL PASS' if val['all_passed'] else 'FAIL'}"
    status_cell = ws4.cell(row=2, column=1, value=status_text)
    status_cell.font = Font(bold=True, size=11, color="2E7D32" if val["all_passed"] else "C62828")

    val_headers = ["Rule", "Description", "Status", "Detail"]
    for col, h in enumerate(val_headers, 1):
        ws4.cell(row=4, column=col, value=h)
    _style_header(ws4, 4, len(val_headers))

    for i, r in enumerate(val["rules"], start=5):
        ws4.cell(row=i, column=1, value=r["rule_id"])
        ws4.cell(row=i, column=2, value=r["description"])
        ws4.cell(row=i, column=3, value=r["status"])
        ws4.cell(row=i, column=4, value=r["detail"])
        fill = _PASS_FILL if r["status"] == "PASS" else _FAIL_FILL
        ws4.cell(row=i, column=3).fill = fill

    end_row = 4 + len(val["rules"])
    _style_data(ws4, 5, end_row, len(val_headers))
    _auto_width(ws4, len(val_headers))

    # Write to bytes
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()
