"""SGO v1.2.1 — Production Cutting Plan PDF Export.

Generates a professional A4 PDF from existing session-state results.
No recalculation — consumes packing_report, recovery_summary, and summary.
"""

import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
)

SGO_VERSION = "v1.2.1"
PAGE_WIDTH, PAGE_HEIGHT = A4


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)
    canvas.drawString(20 * mm, 10 * mm, f"Generated by SGO {SGO_VERSION}")
    canvas.drawRightString(PAGE_WIDTH - 20 * mm, 10 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _make_styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        "SectionTitle", parent=styles["Heading2"],
        spaceAfter=6, textColor=colors.HexColor("#1a1a2e"),
    ))
    styles.add(ParagraphStyle(
        "KpiLabel", parent=styles["Normal"],
        fontSize=9, textColor=colors.grey,
    ))
    styles.add(ParagraphStyle(
        "KpiValue", parent=styles["Normal"],
        fontSize=11, fontName="Helvetica-Bold",
    ))
    return styles


def _kpi_table(rows, col_widths=None):
    if col_widths is None:
        col_widths = [60 * mm, 60 * mm]
    t = Table(rows, colWidths=col_widths)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("ALIGN", (1, 0), (1, -1), "RIGHT"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    return t


def generate_pdf(summary, packing_report, packing_summary,
                 recovery_summary=None, project_name="SGO Project") -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        topMargin=20 * mm, bottomMargin=20 * mm,
        leftMargin=20 * mm, rightMargin=20 * mm,
    )
    styles = _make_styles()
    story = []

    # === PAGE 1: Executive Summary ===
    story.append(Paragraph("Steel Grating Optimizer", styles["Title"]))
    story.append(Paragraph("Production Cutting Plan", styles["Heading2"]))
    story.append(Spacer(1, 6 * mm))

    # Document Metadata
    story.append(Paragraph("Document Information", styles["SectionTitle"]))
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    meta_rows = [
        ["Field", "Value"],
        ["Project Name", project_name],
        ["Generated Date", now],
        ["Generated By", "Steel Grating Optimizer"],
        ["SGO Version", SGO_VERSION],
        ["Algorithm", packing_report["summary"]["algorithm"]],
    ]
    story.append(_kpi_table(meta_rows))
    story.append(Spacer(1, 6 * mm))

    # Project KPI (from summary)
    story.append(Paragraph("Project KPI", styles["SectionTitle"]))
    proj_rows = [
        ["Metric", "Value"],
        ["Sold Area", f"{summary.total_sold_area:.4f} m²"],
        ["Production Area", f"{summary.total_production_area:.4f} m²"],
        ["Raw Material Area", f"{summary.total_raw_material_area:.4f} m²"],
        ["Yield", f"{summary.yield_percent:.2f}%"],
        ["Scrap", f"{summary.scrap_percent:.2f}%"],
    ]
    story.append(_kpi_table(proj_rows))
    story.append(Spacer(1, 6 * mm))

    # Packing KPI (from packing_summary)
    story.append(Paragraph("Packing KPI", styles["SectionTitle"]))
    pk = packing_report["summary"]
    pack_rows = [
        ["Metric", "Value"],
        ["Stock Bars Required", str(pk["stock_lengths_after"])],
        ["Stock Bars Saved", f"{pk['stock_savings']} ({pk['stock_savings_percent']:.2f}%)"],
        ["Utilization", f"{pk['stock_utilization_rate']:.2f}%"],
        ["Raw Material Area (Packing)", f"{pk['total_raw_material_area_m2']:.4f} m²"],
        ["Product Area (Packing)", f"{pk['total_product_area_m2']:.4f} m²"],
        ["Waste Area", f"{pk['total_waste_area_m2']:.4f} m²"],
        ["Kerf Loss", f"{pk['total_kerf_loss_m2']:.4f} m²"],
        ["Reusable Remnant Area", f"{pk['total_reusable_remnant_area_m2']:.4f} m²"],
        ["Length Waste Area", f"{pk['total_length_waste_m2']:.4f} m²"],
    ]
    story.append(_kpi_table(pack_rows))
    story.append(Spacer(1, 6 * mm))

    # Recovery KPI (if available)
    if recovery_summary is not None:
        story.append(Paragraph("Recovery KPI", styles["SectionTitle"]))
        rec_rows = [
            ["Metric", "Value"],
            ["Recovery Rate", f"{recovery_summary.recovery_rate:.2f}%"],
            ["Recovered Area", f"{recovery_summary.recovered_area_m2:.4f} m²"],
            ["Dead Scrap Area", f"{recovery_summary.dead_scrap_area_m2:.4f} m²"],
            ["Remaining Stock Area", f"{recovery_summary.remaining_stock_area_m2:.4f} m²"],
        ]
        story.append(_kpi_table(rec_rows))

    # === PAGE 2+: Production Cutting Plan ===
    story.append(PageBreak())
    story.append(Paragraph("Production Cutting Plan", styles["Title"]))
    story.append(Spacer(1, 4 * mm))

    cutting_plan = packing_report["cutting_plan"]
    for cp in cutting_plan:
        marks_text = ", ".join(f"{e['mark']} × {e['qty']}" for e in cp["entries"])

        header_rows = [
            ["BAR", cp["bin_id"]],
            ["Width", f"{cp['stock_width']:.0f} mm"],
            ["Marks", marks_text],
            ["Panels", str(cp["total_panels"])],
            ["Used Length", f"{cp['total_used']:.0f} mm"],
            ["Remnant", f"{cp['remnant_length']:.0f} mm"],
            ["Classification", cp["remnant_classification"]],
        ]

        t = Table(header_rows, colWidths=[35 * mm, 130 * mm])
        bg = colors.HexColor("#e8f5e9") if cp["remnant_classification"] == "REUSABLE_REMNANT" else (
            colors.HexColor("#fff3e0") if cp["remnant_classification"] == "LENGTH_WASTE" else
            colors.HexColor("#e3f2fd")
        )
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#1a1a2e")),
            ("TEXTCOLOR", (0, 0), (0, -1), colors.white),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("BACKGROUND", (1, 0), (1, -1), bg),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(t)
        story.append(Spacer(1, 3 * mm))

    # === FINAL PAGE: Material Flow + Validation ===
    story.append(PageBreak())
    story.append(Paragraph("Material Flow Summary", styles["Title"]))
    story.append(Spacer(1, 6 * mm))

    flow_rows = [
        ["Stage", "Area (m²)"],
        ["INPUT: Raw Material Area", f"{pk['total_raw_material_area_m2']:.4f}"],
        ["↓", ""],
        ["OUTPUT: Product Area", f"{pk['total_product_area_m2']:.4f}"],
        ["↓", ""],
        ["RECOVERY: Reusable Remnants", f"{pk['total_reusable_remnant_area_m2']:.4f}"],
        ["↓", ""],
        ["LOSS: Kerf Loss", f"{pk['total_kerf_loss_m2']:.4f}"],
        ["LOSS: Length Waste", f"{pk['total_length_waste_m2']:.4f}"],
    ]

    ft = Table(flow_rows, colWidths=[80 * mm, 50 * mm])
    ft.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("ALIGN", (1, 0), (1, -1), "RIGHT"),
        ("ALIGN", (0, 2), (0, 2), "CENTER"),
        ("ALIGN", (0, 4), (0, 4), "CENTER"),
        ("ALIGN", (0, 6), (0, 6), "CENTER"),
        ("TEXTCOLOR", (0, 2), (0, 2), colors.grey),
        ("TEXTCOLOR", (0, 4), (0, 4), colors.grey),
        ("TEXTCOLOR", (0, 6), (0, 6), colors.grey),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(ft)
    story.append(Spacer(1, 10 * mm))

    # Validation Summary
    story.append(Paragraph("Validation Summary (R22–R29)", styles["SectionTitle"]))
    story.append(Spacer(1, 2 * mm))

    val = packing_report["validation"]
    all_passed = val["all_passed"]
    status_text = "ALL PASS" if all_passed else "FAIL"
    status_color = colors.HexColor("#2e7d32") if all_passed else colors.HexColor("#c62828")

    story.append(Paragraph(
        f'<font color="{status_color}">{val["passed"]} / {val["total"]} {status_text}</font>',
        ParagraphStyle("ValidationStatus", parent=styles["Normal"], fontSize=14, fontName="Helvetica-Bold"),
    ))
    story.append(Spacer(1, 4 * mm))

    val_rows = [["Rule", "Description", "Status"]]
    for r in val["rules"]:
        val_rows.append([r["rule_id"], r["description"], r["status"]])

    vt = Table(val_rows, colWidths=[20 * mm, 80 * mm, 20 * mm])
    vt.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (2, 0), (2, -1), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(vt)

    # Build PDF
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()
